import { lexiconIpa, type IpaLexicon } from './ipa-lexicon';

/**
 * IPA do inglês por dicionário: a escrita inglesa não segue regras simples de pronúncia (read/read,
 * through/though/tough…), então cada palavra do vocabulário e das lições tem a sua transcrição,
 * como nos idiomas nórdicos. Pronúncia de referência: inglês internacional, próximo do americano.
 * Palavra fora do dicionário aparece só na grafia, entre ⟨ ⟩.
 */
export const IPA_EN: IpaLexicon = {
  hello: 'həˈloʊ',
  hi: 'haɪ',
  good: 'ɡʊd',
  morning: 'ˈmɔːrnɪŋ',
  afternoon: 'ˌæftərˈnuːn',
  night: 'naɪt',
  goodbye: 'ɡʊdˈbaɪ',
  thanks: 'θæŋks',
  "thank you": 'θæŋk juː',
  "you're": 'jʊr',
  welcome: 'ˈwɛlkəm',
  please: 'pliːz',
  sorry: 'ˈsɑːri',
  yes: 'jɛs',
  no: 'noʊ',
  and: 'ænd',
  or: 'ɔːr',
  very: 'ˈvɛri',
  also: 'ˈɔːlsoʊ',
  i: 'aɪ',
  you: 'juː',
  he: 'hiː',
  she: 'ʃiː',
  we: 'wiː',
  they: 'ðeɪ',
  to: 'tuː',
  be: 'biː',
  am: 'æm',
  is: 'ɪz',
  are: 'ɑːr',
  have: 'hæv',
  has: 'hæz',
  live: 'lɪv',
  speak: 'spiːk',
  go: 'ɡoʊ',
  eat: 'iːt',
  drink: 'drɪŋk',
  like: 'laɪk',
  know: 'noʊ',
  want: 'wɑːnt',
  name: 'neɪm',
  friend: 'frɛnd',
  family: 'ˈfæməli',
  mother: 'ˈmʌðər',
  father: 'ˈfɑːðər',
  brother: 'ˈbrʌðər',
  brothers: 'ˈbrʌðərz',
  sister: 'ˈsɪstər',
  sisters: 'ˈsɪstərz',
  son: 'sʌn',
  daughter: 'ˈdɔːtər',
  house: 'haʊs',
  city: 'ˈsɪti',
  water: 'ˈwɔːtər',
  bread: 'brɛd',
  milk: 'mɪlk',
  coffee: 'ˈkɔːfi',
  wine: 'waɪn',
  dog: 'dɔːɡ',
  cat: 'kæt',
  big: 'bɪɡ',
  small: 'smɔːl',
  today: 'təˈdeɪ',
  tomorrow: 'təˈmɑːroʊ',
  yesterday: 'ˈjɛstərdeɪ',
  one: 'wʌn',
  two: 'tuː',
  three: 'θriː',
  four: 'fɔːr',
  five: 'faɪv',
  six: 'sɪks',
  seven: 'ˈsɛvən',
  eight: 'eɪt',
  nine: 'naɪn',
  ten: 'tɛn',
  twenty: 'ˈtwɛnti',
  monday: 'ˈmʌndeɪ',
  tuesday: 'ˈtuːzdeɪ',
  wednesday: 'ˈwɛnzdeɪ',
  thursday: 'ˈθɜːrzdeɪ',
  friday: 'ˈfraɪdeɪ',
  saturday: 'ˈsætərdeɪ',
  sunday: 'ˈsʌndeɪ',
  red: 'rɛd',
  blue: 'bluː',
  green: 'ɡriːn',
  white: 'waɪt',
  black: 'blæk',
  where: 'wɛr',
  what: 'wʌt',
  how: 'haʊ',
  from: 'frʌm',
  fine: 'faɪn',
  help: 'hɛlp',
  sleep: 'sliːp',
  well: 'wɛl',
  glass: 'ɡlæs',
  of: 'ʌv',
  learn: 'lɜːrn',
  called: 'kɔːld',
  everyone: 'ˈɛvriwʌn',
  english: 'ˈɪŋɡlɪʃ',
  french: 'frɛntʃ',
  portuguese: 'ˌpɔːrtʃʊˈɡiːz',
  brazil: 'brəˈzɪl',
  apple: 'ˈæpəl',
  child: 'tʃaɪld',
  children: 'ˈtʃɪldrən',
  tired: 'ˈtaɪərd',
  nice: 'naɪs',
  meet: 'miːt',
  the: 'ðə',
  this: 'ðɪs',
  that: 'ðæt',
  "don't": 'doʊnt',
  "i'm": 'aɪm',
  "what's": 'wʌts',
  "let's": 'lɛts',
};

export function toIpaEn(text: string): string {
  return lexiconIpa(text, IPA_EN);
}
